  version: '2'
  services:
    nginx:
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - .:/docker-server
        - ./gatgu/nginx/gatgu.conf:/etc/nginx/conf.d
      depends_on:
        - web
    web:  
      build:
        context: ./
        dockerfile : Dockerfile
      command: gunicorn gatgu.wsgi:application --bind 0.0.0.0:8000
      volumes:
        - .:/docker-server
      expose:
        - "8000"
