name: Django CI

on:
  pull_request:
    branches: [ develop ]
jobs:
  django-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup MySQL
        # You may pin to the exact commit or the version.
        # uses: mirromutth/mysql-action@de1fba8b3f90ce8db80f663a7043be3cf3231248
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          mysql database: test_gatgu_db
          mysql user: team-gatgu
          mysql password: gatgu
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Dependencies
        working-directory: ./
        run: |
          python -m pip install --upgrade pip
          pip install -r gatgu/requirements.txt
      - name: Run Tests
        working-directory: ./gatgu
        run: |
          mysql.server start
          python manage.py test
